language: scala

scala:
  - 2.12.3
  - 2.11.11

jdk:
  - oraclejdk8

env:
  - LOGLEVEL=info

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers


before_install:
  - openssl aes-256-cbc -K $encrypted_391999303d86_key -iv $encrypted_391999303d86_iv -in project/gnupg/gpgring.tar.enc -out project/gnupg/gpgring.tar -d
  - tar -xf project/gnupg/gpgring.tar -C project/gnupg/

script:
  - |
    if [[ "$TRAVIS_SCALA_VERSION" = 2.12.* ]]; then
      sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coveralls
    else
      sbt ++$TRAVIS_SCALA_VERSION clean test
    fi

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "sonatypeOpen com.datlinq com.datlinq" +publishSigned sonatypeRelease

branches:
  only:
  - master

notifications:
  slack:
    rooms:
      secure: RIKAb78KANh5uRrUC145vsr3QU72c4J/k8MmpfaBxbYOHYhygvOU5CgcdOPkGYBYm43JQIgg2byZo7Vu14CtAmBvxVArZ2CcKAHvicxQqP7EJhVO9OzUUF45cNU+4rQGiDLIFlw0cbDSd9DHaPdypEcrhF80XDhS+cElrZAI6U/W9VIDuQeiwKUdh+0pWAfLs8mUBXHbCnjdVv0P5E1EdGVi+Btet5LCkw9xZT9TzNrg6dinRUhBETa4qwj5ZKvEjUkKr7MFdKzCgwBCdX1kfyNcwae3A2z/W2Cdr/HNzo+NfktJ9LYBwFMHQHFMvkjZ3GNIjPchN2kS91+wHyleRGdiUw2OTieNqKLXKLHmoM0td1mUteFrS+SjG97Svn3VR/3xHNyutERZxov36J1nErA2FIYWEM39S2M3mU/Llg7PbGB2R0Gacawxns8aAhWukSVXNsUlQnkdsOSVI4AEOPIJh4WHuS5EypapzkEbZEhiF30ofrlXreFKFn5Cr53nk0bldmj6BTlnRiyxUDuk2qWmF20dsbGn2Ppzch3reUhndsnkLnqhwsxci3LuqY6aw47T/c8svERI9CFEgsqQUw0Dt4EeLPoEwfkrPiDiseZtj4Y0q0lsQp+RcDIOPLGf4lXBi19n4uBiWKSPI75nLgiPpHEiAuyBlH+HtW8DT+o=
