language: scala
scala:
  - 2.12.3
jdk:
  - oraclejdk8
env:
  - LOGLEVEL=info
before_install:
 - echo "$PGP_SECRET" | base64 --decode | gpg --import
 - echo "$PGP_TRUST" | base64 --decode | gpg --import-ownertrust
 - openssl aes-256-cbc -K $encrypted_391999303d86_key -iv $encrypted_391999303d86_iv -in gpg.credentials.enc -out gpg.credentials -d
script:
  - sbt clean coverage test coverageReport
  - sbt coveralls
after_success:
  - sbt "pgp-cmd list-keys"
  - gpg --list-keys --fingerprint
  - gpg --list-secret-keys --fingerprint
  - sbt "sonatypeOpen com.datlinq com.datlinq"
  - sbt publishSigned
  - sbtsonatypeRelease
#  - sbt publish
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      secure: RIKAb78KANh5uRrUC145vsr3QU72c4J/k8MmpfaBxbYOHYhygvOU5CgcdOPkGYBYm43JQIgg2byZo7Vu14CtAmBvxVArZ2CcKAHvicxQqP7EJhVO9OzUUF45cNU+4rQGiDLIFlw0cbDSd9DHaPdypEcrhF80XDhS+cElrZAI6U/W9VIDuQeiwKUdh+0pWAfLs8mUBXHbCnjdVv0P5E1EdGVi+Btet5LCkw9xZT9TzNrg6dinRUhBETa4qwj5ZKvEjUkKr7MFdKzCgwBCdX1kfyNcwae3A2z/W2Cdr/HNzo+NfktJ9LYBwFMHQHFMvkjZ3GNIjPchN2kS91+wHyleRGdiUw2OTieNqKLXKLHmoM0td1mUteFrS+SjG97Svn3VR/3xHNyutERZxov36J1nErA2FIYWEM39S2M3mU/Llg7PbGB2R0Gacawxns8aAhWukSVXNsUlQnkdsOSVI4AEOPIJh4WHuS5EypapzkEbZEhiF30ofrlXreFKFn5Cr53nk0bldmj6BTlnRiyxUDuk2qWmF20dsbGn2Ppzch3reUhndsnkLnqhwsxci3LuqY6aw47T/c8svERI9CFEgsqQUw0Dt4EeLPoEwfkrPiDiseZtj4Y0q0lsQp+RcDIOPLGf4lXBi19n4uBiWKSPI75nLgiPpHEiAuyBlH+HtW8DT+o=
